apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: news-alligator
  namespace: argocd
spec:
  project: default
  destination:
    namespace: news-alligator
    server: https://kubernetes.default.svc
  source:
    path: manifest/helm/news-alligator
    repoURL: https://github.com/antonchaban/news-aggregator.git
    targetRevision: feature/argo-cd
    helm:
      values: |
        postgresql:
          auth:
            username: "testVal"
            password: "testVal"
        aws:
          secretAccessKey: "badtest" 
          accessKeyId: "badtest" 

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 3
    syncOptions:
      - CreateNamespace=true