apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-generator
  namespace: argocd
spec:
  project: default
  destination:
    namespace: news-alligator
    server: https://kubernetes.default.svc
  source:
    path: manifest/helm/secret-generator
    repoURL: https://github.com/antonchaban/news-aggregator.git
    targetRevision: feature/argo-cd

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 3
    syncOptions:
      - CreateNamespace=true