apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-generator
  namespace: argocd
spec:
  project: default
  destination:
    namespace: news-alligator
    server: https://kubernetes.default.svc
  source:
    path: manifest/helm/secret-generator
    repoURL: https://github.com/antonchaban/news-aggregator.git
    targetRevision: master
    helm:
      values: |  # Provide the necessary Helm values
        ecrSecretName: "ecr-secret"
        ecrOperatorSecretName: "ecr-operator-secret"
        ecrSchedule: "* * * * *"
        aws:
          secretAccessKey: "badtest" 
          accessKeyId: "badtest" 
          accountId: "406477933661"
          region: "us-west-2"

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 3
    syncOptions:
      - CreateNamespace=true