---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-aggregator-com-teamdev-v1-source
  failurePolicy: Fail
  name: msource.kb.io
  rules:
  - apiGroups:
    - aggregator.com.teamdev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sources
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-aggregator-com-teamdev-v1-source
  failurePolicy: Fail
  name: vsource.kb.io
  rules:
  - apiGroups:
    - aggregator.com.teamdev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sources
  sideEffects: None
