apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-helper-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
stringData:
  AWS_SECRET_ACCESS_KEY: {{ required "aws.secretAccessKey is required" .Values.aws.secretAccessKey | quote }}
  AWS_ACCESS_KEY_ID: {{ required "aws.accessKeyId is required" .Values.aws.accessKeyId | quote }}
  AWS_ACCOUNT: {{ required "aws.accountId is required" .Values.aws.accountId | quote }}