apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-registry-helper
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.ecrSchedule | quote}}
  successfulJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-news-alligator
          containers:
            - name: ecr-registry-helper
              image: odaniait/aws-kubectl:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: NAMESPACE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              envFrom:
                - secretRef:
                    name: ecr-registry-helper-secrets
                - configMapRef:
                    name: ecr-registry-helper-cm
              command:
                - /bin/sh
                - -c
                - |-
                  ECR_TOKEN=$(aws ecr get-login-password --region ${AWS_REGION})
                  DOCKER_CONFIG_JSON=$(echo -n "{\"auths\":{\"${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com\":{\"username\":\"AWS\",\"password\":\"${ECR_TOKEN}\"}}}")
                  PATCH_JSON=$(echo -n $DOCKER_CONFIG_JSON | base64 | tr -d '\n')
                  kubectl patch secret $DOCKER_SECRET_NAME -n $NAMESPACE_NAME --type='json' -p='[{"op": "replace", "path": "/data/.dockerconfigjson", "value":"'"$PATCH_JSON"'"}]'
                  echo "Secret was successfully patched at $(date)"
          restartPolicy: Never
