version: '3'

tasks:
  build:
    cmds:
      - docker build . -f Dockerfile -t antohachaban/news-alligator-web
    desc: Build the Docker image

  run:
    cmds:
      - docker run -d -v news-aggregator-backups:/root/backups -p 8080:8080 antohachaban/news-alligator-web
    desc: Run the Docker container

  stop:
    cmds:
      - docker stop $(docker ps -q --filter ancestor=antohachaban/news-alligator-web)
    desc: Stop the Docker container

  push:
    cmds:
      - docker push antohachaban/news-alligator-web
    desc: Push the Docker image to the registry

  test:
    cmds:
      - go test -v ./...
    desc: Run tests

  pull:
    cmds:
      - docker pull antohachaban/news-alligator-web
    desc: Pull the Docker image from the registry

  swag:
    cmds:
      - swag init -d .,../../../pkg/handler/web,../../../pkg/model
    desc: Initialize Swagger documentation

  run-local:
    env:
      PORT: 8080
      SAVES_DIR: ./backups
      CERT_FILE: ./server.crt
      KEY_FILE: ./server.key
    cmds:
      - go build -o web.exe ./cmd/news-alligator/web
      - ./web.exe
    desc: Build and run the main Go file locally with environment variables


  mockgen:
    desc: Run mockgen for generating mocks
    cmds:
      - mockgen -destination=pkg/service/mocks/mock_source_service.go -package=mocks github.com/antonchaban/news-aggregator/pkg/service SourceService
      - mockgen -destination=pkg/storage/mocks/mock_article.go -package=mocks github.com/antonchaban/news-aggregator/pkg/storage ArticleStorage
      - mockgen -destination=pkg/service/mocks/mock_article_service.go -package=mocks github.com/antonchaban/news-aggregator/pkg/service ArticleService
      - mockgen -destination=pkg/storage/mocks/mock_source.go -package=mocks github.com/antonchaban/news-aggregator/pkg/storage SourceStorage




  run-postgres:
    cmds:
      - docker run --name=news-alligator-db -e POSTGRES_PASSWORD='qwerty' -p 5436:5432 -d --rm postgres
    desc: Run the PostgreSQL container

  init-db:
    cmds:
      - migrate -path ./schema -database 'postgres://postgres:qwerty@0.0.0.0:5436/postgres?sslmode=disable' up
    desc: Initialize the database