version: '3'

vars:
  VERSION: '{{.VERSION | default "latest"}}'
  FETCHER_IMAGE_NAME: "406477933661.dkr.ecr.us-west-2.amazonaws.com/antohachaban/news-fetcher:{{.VERSION}}"


tasks:
  build:
    cmds:
      - docker build -t {{.FETCHER_IMAGE_NAME}} -f Dockerfile.fetcher .

  push:
    cmds:
      - docker push {{.FETCHER_IMAGE_NAME}}