# Application-specific values
replicaCount: 1
containerPort: 443
imageName: "antohachaban/news-alligator-web:0.2.4"
namespace: "news-alligator"
serviceAccount: "news-alligator-sa"

tlsSecretName: "teamdev-tls-secret"
certvalues:
  commonName: "https://teamdev.com/"
  duration: "8760h"
  organization: "Team Dev"
  dnsName: "teamdev.com"

# Resource requests and limits for the application container
resources:
  limits:
    cpu: "500m"
    memory: "128Mi"
  requests:
    cpu: "250m"
    memory: "64Mi"

# Autoscaling settings
autoscaling:
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

  vpa:
    enabled: true
    minAllowed:
      cpu: "200m"
      memory: "64Mi"
    maxAllowed:
      cpu: "2"
      memory: "1Gi"

# PostgreSQL configuration from the Bitnami chart
postgresql:
  fullnameOverride: "postgres"
  auth:
    database: "postgres"
    username: "admin"
    password: "admin"
  primary:
    persistence:
      size: 2Gi
      mountPath: /bitnami/postgresql

# CronJob settings
cronjob:
  enabled: true
  name: "news-fetcher-cronjob"
  schedule: "0 0 * * *" # Default: Run once a day at midnight
  image:
    name: "antohachaban/news-fetcher:0.1"
  env:
    secretName: "news-alligator-secret"
    configMapName: "news-alligator-config"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
