postgresql:
  fullnameOverride: postgres
  auth:
    database: "postgres"
    username: "admin"
    password: "admin"
  primary:
    persistence:
      size: 2Gi
      mountPath: /var/lib/postgresql/data