{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}-cronjob
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: news-fetcher
              image: {{ .Values.cronjob.image.name }}
              envFrom:
                - secretRef:
                    name: {{ .Values.cronjob.env.secretName }}
                - configMapRef:
                    name: {{ .Values.cronjob.env.configMapName }}
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
{{- end }}
