apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount | default "default" }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.cronjob.name }}-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
    - kind: ServiceAccount
      name: {{ .Values.cronjob.name }}-sa
      namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.cronjob.name }}-role
  apiGroup: rbac.authorization.k8s.io