apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER: {{ required "postgresql.auth.username is required" .Values.postgresql.auth.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ required "postgresql.auth.password is required" .Values.postgresql.auth.password | b64enc | quote }}
