apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount | default "default" }}
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cronjob.name}}-sa
  namespace: {{ .Values.namespace }}