---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - aggregator.com.teamdev
  resources:
  - hotnews
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aggregator.com.teamdev
  resources:
  - hotnews/finalizers
  verbs:
  - update
- apiGroups:
  - aggregator.com.teamdev
  resources:
  - hotnews/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - aggregator.com.teamdev
  resources:
  - sources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aggregator.com.teamdev
  resources:
  - sources/finalizers
  verbs:
  - update
- apiGroups:
  - aggregator.com.teamdev
  resources:
  - sources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
