# permissions for end users to view sources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: source-viewer-role
rules:
- apiGroups:
  - aggregator.com.teamdev
  resources:
  - sources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aggregator.com.teamdev
  resources:
  - sources/status
  verbs:
  - get
