apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: news-alligator
  name: news-fetcher-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
