apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: news-alligator
  name: news-alligator-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
