version: '3'

vars:
  IMG: "antohachaban/alligator-operator:0.2.4"
  CONTAINER_TOOL: "docker"
  KUBECTL: "kubectl"
  KUSTOMIZE_VERSION: "v5.4.2"
  CONTROLLER_TOOLS_VERSION: "v0.15.0"
  GOLANGCI_LINT_VERSION: "v1.59.1"
  PLATFORMS: "linux/arm64,linux/amd64,linux/s390x,linux/ppc64le"
  ignore_not_found: "false"

tasks:
  default:
    cmds:
      - task: build

  help:
    desc: "Display help"
    cmds:
      - |
        echo "Usage:"
        echo "  task [target]"
        echo ""
        echo "Targets:"
        task: list

  list:
    desc: "List available tasks"
    cmds:
      - task: help

  manifests:
    desc: "Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects."
    cmds:
      - |
        LOCALBIN=$(pwd)/bin
        CONTROLLER_GEN=$LOCALBIN/controller-gen
        $CONTROLLER_GEN rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases

  generate:
    desc: "Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations."
    cmds:
      - |
        LOCALBIN=$(pwd)/bin
        CONTROLLER_GEN=$LOCALBIN/controller-gen
        $CONTROLLER_GEN object:headerFile="hack/boilerplate.go.txt" paths="./..."

  fmt:
    desc: "Run go fmt against code."
    cmds:
      - "go fmt ./..."

  vet:
    desc: "Run go vet against code."
    cmds:
      - "go vet ./..."

  build:
    desc: "Build manager binary."
    cmds:
      - task: manifests
      - task: generate
      - task: fmt
      - task: vet
      - "go build -o bin/manager cmd/main.go"

  docker-build:
    desc: "Build docker image with the manager."
    cmds:
      - "{{.CONTAINER_TOOL}} build -t {{.IMG}} ."

  docker-push:
    desc: "Push docker image with the manager."
    cmds:
      - "{{.CONTAINER_TOOL}} push {{.IMG}}"

  install:
    desc: "Install CRDs into the K8s cluster specified in ~/.kube/config."
    cmds:
      - task: manifests
      - "{{.KUSTOMIZE}} build config/crd | {{.KUBECTL}} apply -f -"

  uninstall:
    desc: "Uninstall CRDs from the K8s cluster specified in ~/.kube/config."
    cmds:
      - task: manifests
      - "{{.KUSTOMIZE}} build config/crd | {{.KUBECTL}} delete --ignore-not-found={{.ignore_not_found}} -f -"

  deploy:
    desc: "Deploy controller to the K8s cluster specified in ~/.kube/config."
    cmds:
      - task: manifests
      - |
        LOCALBIN=$(pwd)/bin
        KUSTOMIZE=$LOCALBIN/kustomize
        cd config/manager && $KUSTOMIZE edit set image controller={{.IMG}}
        cd - # Return to previous directory
        $KUSTOMIZE build config/default | {{.KUBECTL}} apply -f -

  undeploy:
    desc: "Undeploy controller from the K8s cluster specified in ~/.kube/config."
    cmds:
      - |
        LOCALBIN=$(pwd)/bin
        KUSTOMIZE=$LOCALBIN/kustomize
        $KUSTOMIZE build config/default | {{.KUBECTL}} delete --ignore-not-found={{.ignore_not_found}} -f -
