apiVersion: v1
kind: Service
metadata:
  name: news-alligator-service
  namespace: news-alligator
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: 443
  selector:
    app: news-alligator