# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - master
      - feature/cicd-actions
  pull_request:
    branches:
      - master
      - feature/**

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.51.2


  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install task
        uses: arduino/setup-task@v2

      - name: Build
        run: task build-go

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install task
        uses: arduino/setup-task@v2

      - name: Test
        run: task test


  finish:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    if: needs.build.result == 'success' && needs.test.result == 'success'
    steps:
      - run: echo "Build and test are successful"
