# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - master
      - feature/cicd-actions
  pull_request:
    branches:
      - master
      - feature/**

jobs:
  mockgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install task
        uses: arduino/setup-task@v2

      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@v1.6.0

      - name: Generate mocks
        run: task mockgen

  build:
    runs-on: ubuntu-latest
    needs: mockgen
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install task
        uses: arduino/setup-task@v2

      - name: Build
        run: task build-go

  test:
    runs-on: ubuntu-latest
    needs: mockgen
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install task
        uses: arduino/setup-task@v2

      - name: Test
        run: task test

  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install task
        uses: arduino/setup-task@v2

      - name: Tidy
        run: task tidy

  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install task
        uses: arduino/setup-task@v2

      - name: Vet
        run: task vet

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install task
        uses: arduino/setup-task@v2

      - name: Format
        run: task format

  finish:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    if: needs.build.result == 'success' && needs.test.result == 'success'
    steps:
      - run: echo "Build and test are successful"
