name: Release Please

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Release Please
        uses: google-github-actions/release-please-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
