name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v4

      - name: Install task
        if: ${{ steps.release.outputs.release_created }}
        uses: arduino/setup-task@v2

      - name: Set up Docker Buildx
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        if: ${{ steps.release.outputs.release_created }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        if: ${{ steps.release.outputs.release_created }}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push images to ECR using Taskfile
        if: ${{ steps.release.outputs.release_created }}
        run: |
          task push-all VERSION=${{ steps.release.outputs.version }}